### ISSUE TITLE
Nuevo artículo: faltan campos

### ISSUE THREAD

**Issue by anassa** [anassa/aleph_backend#2]
Faltan los siguientes campos: código (que tiene que estar sin edición), Ajuste de inventario con un objeto "on off" para editar o no el campo. 
![nuevo articulo datos moqups](https://cloud.githubusercontent.com/assets/4991886/20437999/c2fe03b6-ad94-11e6-916d-695b81c2487d.png)

**Comment by nguidi** [comment]
El código se asigna después de crear el articulo ya que para poder crear un código antes de crear un articulo tendría que asegurarme de que el código sea único, almacenarlo para verificar que no se lo de a ningún otra persona que acceda a la vista de nuevo articulo y en caso de que la persona no decida crear el articulo descartar el código generado.

Tendría que armar una gestión paralela de códigos solo para poder mostrarlo en la pantalla de creación. O bien ir creando artículos temporales sobre la marcha y descartarlos en caso de que no se cree el articulo (por algun timeout o algo parecido)

Creo que esta mal pensado. Es como intentar crear un ID para un documento antes de crear el documento.

Tampoco podría traer el ultimo código creado y sumarle un uno ya que si otra persona accede desde otro navegador a esta vista antes de que cree el articulo se le asignaría el mismo código.

Porque no mostramos el código una vez creada el articulo, como un resumen del articulo creado.

El campo ajuste inventario solo es visible cuando se edita el articulo (como dice en la descripción de caso de uso).  Esto se agrego en el commit que acabo de realizar.

**Comment by anassa** [comment]
Ok lo que si cuando entra en la edición del articulo así como se muestra el campo Ajuste de Inventario, que se muestre el código del artículo sin permitir editarlo.
